# -*- coding: utf-8 -*-
"""Stroke classification.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UWI895gIOOt8ZIfF_znobeij2uI6ObHy
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import SGDClassifier
from sklearn.metrics import accuracy_score, classification_report

data = pd.read_csv('/content/drive/MyDrive/ML AND DL/Datasets/healthcare-dataset-stroke-data.csv')
data_encoded = pd.get_dummies(data, columns=['gender','ever_married','work_type','Residence_type','smoking_status'])
print(data_encoded.describe())
print(data_encoded.isnull().sum())

X = data_encoded.drop(['bmi','stroke'],axis=1)
y = data_encoded['stroke']

X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.2, random_state=42)

sgd_clf = SGDClassifier(random_state=42)
sgd_clf.fit(X_train,y_train)

y_pred = sgd_clf.predict(X_test)

accuracy = accuracy_score(y_test,y_pred)
report = classification_report(y_test,y_pred)

print(f"accuracy:{accuracy}\n Classification report:\n {report}")

